### ISSUE TITLE
PS3 Disconnects players randomly

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#19]
If you set the automatic idle shutdown to 1 minute it will stop the player server even if there is players online on that Playerservers, The disconnect message is "[Proxy] Lost connection to server".

A fix that could work after you fix this incase other people have this issue is trying setting it to 5 minutes.

**Comment by OpenSource03** [comment]
So this happens only if you set shutdown timer to one minute?

**Comment by megatron0001** [comment]
GeyserMC issue, It is now fixed.
