### ISSUE TITLE
PS3 /config editing does not work.

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#20]
When you do /config and try to click on a plugin config yml it does not popup with an editor.

**Comment by OpenSource03** [comment]
Only config editor? /menu works? And like config menu opens, but it doesn't provide you with edit URL?

**Comment by OpenSource03** [comment]
This has been fixed. A simple restart of BungeeCord (or Daemon) + affected subservers should fix the issue.
