### ISSUE TITLE
Bunch of recommends to add

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#21]
- [ ] I think there should be a way to name the playerservers like when creating it, the player has an option to give it a name,
- [ ] a way for a player to have more than 1 servers if they have permissions such as playerservers.limit.[Number] default is 1 or that can be changed in the config,
- [ ] another idea when a server is online is should make it on the /menu where all the servers are it should put the head at the top like a priority.

**Comment by OpenSource03** [comment]
Please make 3 separate issues for these three things to keep it all organised :)
