### ISSUE TITLE
OOM killer disable does not work

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#22]
If you have the OOM killer set to true (to disable it) it will OOM kill docker servers.

**Comment by OpenSource03** [comment]
Hi, we can not confirm this issue yet. The issue seems to be gone for other customers as soon as they disable OOM killer. Keep in mind that you need to recreate your server as you disable OOM killer (at least for now). Try removing it and creating it again and reopen the issue if it happens again.
