### ISSUE TITLE
[PSServerCore] Server Player Limits

### ISSUE THREAD

**Issue by simplylate** [arcadiadevs/playerservers-everything#25]
On editing the player limit using the /menu command you can set your playercount higher than intended. 
It will say "Failure!" "No more than 10" but upon re-entering the /menu it's been set.

**Comment by OpenSource03** [comment]
Lol, I see 😂 You can reboot BungeeCord (or Daemon, if you're running in non-pterodactyl node) and the servers affected to fix it - PSServerCore update will be downloaded automatically.
