### ISSUE TITLE
Ability to edit PSServerCore using /config.

### ISSUE THREAD

**Issue by simplylate** [arcadiadevs/playerservers-everything#29]
Users are able to edit the configuration using /config's menu.

**Comment by OpenSource03** [comment]
Sorry, not sure I understand this one...

**Comment by simplylate** [comment]
Editing the PlayerServers plugin on servers (ie: config.yml) is possible using /config.

**Comment by OpenSource03** [comment]
Fixed. Update will **SOON** be automatically available after restart of your bungee (or Daemon if you're running in Docker mode) and affected subservers.
