### ISSUE TITLE
Re: issues have not been fixed

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#41]
[Marko675](https://github.com/Marko675) commented [2 days ago](https://github.com/arcadiadevs/playerservers-everything/issues/38#issuecomment-1440486699)
This issue has been solved

Also PLEASE tell me how to do the mount

**Comment by OpenSource03** [comment]
The fix is not live yet. Will be this night, or later. Ask me on Discord if you still don't see the issue fixed by tomorrow night :)

I'll write a guide today.
