### ISSUE TITLE
[Reopen] Auto Shutdown does not work 

### ISSUE THREAD

**Issue by megatron0001** [arcadiadevs/playerservers-everything#47]
The autoshutdown still does not work, I have restart my whole network and subservers effected.

**Comment by expxx** [comment]
No new jar was released, no duh it doesn't work yet.

**Comment by megatron0001** [comment]
> No new jar was released, no duh it doesn't work yet.

First of all, the player management was fixed and another bug which means something did get released also there isnt no new jar theres an autoupdater for a reason.

**Comment by OpenSource03** [comment]
The only way for this to work is to disable restart on crash in /etc/pterodactyl/config.yml (for your wings)

Further releases of [arcadiadevs/wings](https://github.com/arcadiadevs/wings) will have it disabled by default.

**Comment by megatron0001** [comment]
> The only way for this to work is to disable restart on crash in /etc/pterodactyl/config.yml (for your wings)
> 
> Further releases of [arcadiadevs/wings](https://github.com/arcadiadevs/wings) will have it disabled by default.

It does not even attempt to shutdown the server nor restart it.
