### ISSUE TITLE
hope the servers on /menu can be sorted based on the number of players

### ISSUE THREAD

**Issue by steven11304** [arcadiadevs/playerservers-everything#56]
I hope that the /menu can be sorted based on the number of players, with servers having more players displayed at the top.
I also hope to have an option to disable offline servers from being shown on /menu

**Comment by Marko675** [comment]
The upcoming update will include the ability to sort servers based on player count and an option to hide offline servers.

**Comment by megatron0001** [comment]
I can't even use /menu

**Comment by steven11304** [comment]
> I can't even use /menu

I  can
